// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StatList.proto

package com.illegalaccess.rest.monitor.client.vo.proto;

public final class InvocationStatListProto {
  private InvocationStatListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InvocationStatListVOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sourceProto.InvocationStatListVO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
     */
    java.util.List<InvocationStatVO>
        getStatVOListList();
    /**
     * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
     */
    InvocationStatVO getStatVOList(int index);
    /**
     * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
     */
    int getStatVOListCount();
    /**
     * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
     */
    java.util.List<? extends InvocationStatVOOrBuilder>
        getStatVOListOrBuilderList();
    /**
     * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
     */
    InvocationStatVOOrBuilder getStatVOListOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code sourceProto.InvocationStatListVO}
   */
  public  static final class InvocationStatListVO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sourceProto.InvocationStatListVO)
      InvocationStatListVOOrBuilder {
    // Use InvocationStatListVO.newBuilder() to construct.
    private InvocationStatListVO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InvocationStatListVO() {
      statVOList_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private InvocationStatListVO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                statVOList_ = new java.util.ArrayList<InvocationStatVO>();
                mutable_bitField0_ |= 0x00000001;
              }
              statVOList_.add(
                  input.readMessage(InvocationStatVO.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          statVOList_ = java.util.Collections.unmodifiableList(statVOList_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return InvocationStatListProto.internal_static_sourceProto_InvocationStatListVO_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return InvocationStatListProto.internal_static_sourceProto_InvocationStatListVO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InvocationStatListVO.class, Builder.class);
    }

    public static final int STATVOLIST_FIELD_NUMBER = 1;
    private java.util.List<InvocationStatVO> statVOList_;
    /**
     * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
     */
    public java.util.List<InvocationStatVO> getStatVOListList() {
      return statVOList_;
    }
    /**
     * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
     */
    public java.util.List<? extends InvocationStatVOOrBuilder>
        getStatVOListOrBuilderList() {
      return statVOList_;
    }
    /**
     * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
     */
    public int getStatVOListCount() {
      return statVOList_.size();
    }
    /**
     * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
     */
    public InvocationStatVO getStatVOList(int index) {
      return statVOList_.get(index);
    }
    /**
     * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
     */
    public InvocationStatVOOrBuilder getStatVOListOrBuilder(
        int index) {
      return statVOList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < statVOList_.size(); i++) {
        output.writeMessage(1, statVOList_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < statVOList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, statVOList_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof InvocationStatListVO)) {
        return super.equals(obj);
      }
      InvocationStatListVO other = (InvocationStatListVO) obj;

      boolean result = true;
      result = result && getStatVOListList()
          .equals(other.getStatVOListList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getStatVOListCount() > 0) {
        hash = (37 * hash) + STATVOLIST_FIELD_NUMBER;
        hash = (53 * hash) + getStatVOListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static InvocationStatListVO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InvocationStatListVO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InvocationStatListVO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InvocationStatListVO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InvocationStatListVO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static InvocationStatListVO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static InvocationStatListVO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static InvocationStatListVO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static InvocationStatListVO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static InvocationStatListVO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(InvocationStatListVO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sourceProto.InvocationStatListVO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sourceProto.InvocationStatListVO)
        InvocationStatListVOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return InvocationStatListProto.internal_static_sourceProto_InvocationStatListVO_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return InvocationStatListProto.internal_static_sourceProto_InvocationStatListVO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                InvocationStatListVO.class, Builder.class);
      }

      // Construct using com.illegalaccess.rest.monitor.client.vo.proto.InvocationStatListProto.InvocationStatListVO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStatVOListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (statVOListBuilder_ == null) {
          statVOList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          statVOListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return InvocationStatListProto.internal_static_sourceProto_InvocationStatListVO_descriptor;
      }

      public InvocationStatListVO getDefaultInstanceForType() {
        return InvocationStatListVO.getDefaultInstance();
      }

      public InvocationStatListVO build() {
        InvocationStatListVO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public InvocationStatListVO buildPartial() {
        InvocationStatListVO result = new InvocationStatListVO(this);
        int from_bitField0_ = bitField0_;
        if (statVOListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            statVOList_ = java.util.Collections.unmodifiableList(statVOList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.statVOList_ = statVOList_;
        } else {
          result.statVOList_ = statVOListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof InvocationStatListVO) {
          return mergeFrom((InvocationStatListVO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(InvocationStatListVO other) {
        if (other == InvocationStatListVO.getDefaultInstance()) return this;
        if (statVOListBuilder_ == null) {
          if (!other.statVOList_.isEmpty()) {
            if (statVOList_.isEmpty()) {
              statVOList_ = other.statVOList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStatVOListIsMutable();
              statVOList_.addAll(other.statVOList_);
            }
            onChanged();
          }
        } else {
          if (!other.statVOList_.isEmpty()) {
            if (statVOListBuilder_.isEmpty()) {
              statVOListBuilder_.dispose();
              statVOListBuilder_ = null;
              statVOList_ = other.statVOList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              statVOListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStatVOListFieldBuilder() : null;
            } else {
              statVOListBuilder_.addAllMessages(other.statVOList_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        InvocationStatListVO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (InvocationStatListVO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<InvocationStatVO> statVOList_ =
        java.util.Collections.emptyList();
      private void ensureStatVOListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          statVOList_ = new java.util.ArrayList<InvocationStatVO>(statVOList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          InvocationStatVO, InvocationStatVO.Builder, InvocationStatVOOrBuilder> statVOListBuilder_;

      /**
       * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
       */
      public java.util.List<InvocationStatVO> getStatVOListList() {
        if (statVOListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(statVOList_);
        } else {
          return statVOListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
       */
      public int getStatVOListCount() {
        if (statVOListBuilder_ == null) {
          return statVOList_.size();
        } else {
          return statVOListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
       */
      public InvocationStatVO getStatVOList(int index) {
        if (statVOListBuilder_ == null) {
          return statVOList_.get(index);
        } else {
          return statVOListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
       */
      public Builder setStatVOList(
          int index, InvocationStatVO value) {
        if (statVOListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStatVOListIsMutable();
          statVOList_.set(index, value);
          onChanged();
        } else {
          statVOListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
       */
      public Builder setStatVOList(
          int index, InvocationStatVO.Builder builderForValue) {
        if (statVOListBuilder_ == null) {
          ensureStatVOListIsMutable();
          statVOList_.set(index, builderForValue.build());
          onChanged();
        } else {
          statVOListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
       */
      public Builder addStatVOList(InvocationStatVO value) {
        if (statVOListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStatVOListIsMutable();
          statVOList_.add(value);
          onChanged();
        } else {
          statVOListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
       */
      public Builder addStatVOList(
          int index, InvocationStatVO value) {
        if (statVOListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStatVOListIsMutable();
          statVOList_.add(index, value);
          onChanged();
        } else {
          statVOListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
       */
      public Builder addStatVOList(
          InvocationStatVO.Builder builderForValue) {
        if (statVOListBuilder_ == null) {
          ensureStatVOListIsMutable();
          statVOList_.add(builderForValue.build());
          onChanged();
        } else {
          statVOListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
       */
      public Builder addStatVOList(
          int index, InvocationStatVO.Builder builderForValue) {
        if (statVOListBuilder_ == null) {
          ensureStatVOListIsMutable();
          statVOList_.add(index, builderForValue.build());
          onChanged();
        } else {
          statVOListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
       */
      public Builder addAllStatVOList(
          Iterable<? extends InvocationStatVO> values) {
        if (statVOListBuilder_ == null) {
          ensureStatVOListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, statVOList_);
          onChanged();
        } else {
          statVOListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
       */
      public Builder clearStatVOList() {
        if (statVOListBuilder_ == null) {
          statVOList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          statVOListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
       */
      public Builder removeStatVOList(int index) {
        if (statVOListBuilder_ == null) {
          ensureStatVOListIsMutable();
          statVOList_.remove(index);
          onChanged();
        } else {
          statVOListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
       */
      public InvocationStatVO.Builder getStatVOListBuilder(
          int index) {
        return getStatVOListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
       */
      public InvocationStatVOOrBuilder getStatVOListOrBuilder(
          int index) {
        if (statVOListBuilder_ == null) {
          return statVOList_.get(index);  } else {
          return statVOListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
       */
      public java.util.List<? extends InvocationStatVOOrBuilder>
           getStatVOListOrBuilderList() {
        if (statVOListBuilder_ != null) {
          return statVOListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(statVOList_);
        }
      }
      /**
       * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
       */
      public InvocationStatVO.Builder addStatVOListBuilder() {
        return getStatVOListFieldBuilder().addBuilder(
            InvocationStatVO.getDefaultInstance());
      }
      /**
       * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
       */
      public InvocationStatVO.Builder addStatVOListBuilder(
          int index) {
        return getStatVOListFieldBuilder().addBuilder(
            index, InvocationStatVO.getDefaultInstance());
      }
      /**
       * <code>repeated .sourceProto.InvocationStatVO statVOList = 1;</code>
       */
      public java.util.List<InvocationStatVO.Builder>
           getStatVOListBuilderList() {
        return getStatVOListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          InvocationStatVO, InvocationStatVO.Builder, InvocationStatVOOrBuilder>
          getStatVOListFieldBuilder() {
        if (statVOListBuilder_ == null) {
          statVOListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              InvocationStatVO, InvocationStatVO.Builder, InvocationStatVOOrBuilder>(
                  statVOList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          statVOList_ = null;
        }
        return statVOListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:sourceProto.InvocationStatListVO)
    }

    // @@protoc_insertion_point(class_scope:sourceProto.InvocationStatListVO)
    private static final InvocationStatListVO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new InvocationStatListVO();
    }

    public static InvocationStatListVO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InvocationStatListVO>
        PARSER = new com.google.protobuf.AbstractParser<InvocationStatListVO>() {
      public InvocationStatListVO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new InvocationStatListVO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InvocationStatListVO> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<InvocationStatListVO> getParserForType() {
      return PARSER;
    }

    public InvocationStatListVO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InvocationStatVOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sourceProto.InvocationStatVO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 invokeTimes = 1;</code>
     */
    long getInvokeTimes();

    /**
     * <code>optional int64 invokeFailureTimes = 2;</code>
     */
    long getInvokeFailureTimes();

    /**
     * <code>optional int64 invokeTotalCost = 3;</code>
     */
    long getInvokeTotalCost();

    /**
     * <code>optional int64 invokeMinCost = 4;</code>
     */
    long getInvokeMinCost();

    /**
     * <code>optional int64 invokeMaxCost = 5;</code>
     */
    long getInvokeMaxCost();

    /**
     * <code>optional int64 reportTimestamp = 6;</code>
     */
    long getReportTimestamp();

    /**
     * <code>optional string methodName = 7;</code>
     */
    String getMethodName();
    /**
     * <code>optional string methodName = 7;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>optional string host = 8;</code>
     */
    String getHost();
    /**
     * <code>optional string host = 8;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>optional string app = 9;</code>
     */
    String getApp();
    /**
     * <code>optional string app = 9;</code>
     */
    com.google.protobuf.ByteString
        getAppBytes();
  }
  /**
   * Protobuf type {@code sourceProto.InvocationStatVO}
   */
  public  static final class InvocationStatVO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sourceProto.InvocationStatVO)
      InvocationStatVOOrBuilder {
    // Use InvocationStatVO.newBuilder() to construct.
    private InvocationStatVO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InvocationStatVO() {
      invokeTimes_ = 0L;
      invokeFailureTimes_ = 0L;
      invokeTotalCost_ = 0L;
      invokeMinCost_ = 0L;
      invokeMaxCost_ = 0L;
      reportTimestamp_ = 0L;
      methodName_ = "";
      host_ = "";
      app_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private InvocationStatVO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              invokeTimes_ = input.readInt64();
              break;
            }
            case 16: {

              invokeFailureTimes_ = input.readInt64();
              break;
            }
            case 24: {

              invokeTotalCost_ = input.readInt64();
              break;
            }
            case 32: {

              invokeMinCost_ = input.readInt64();
              break;
            }
            case 40: {

              invokeMaxCost_ = input.readInt64();
              break;
            }
            case 48: {

              reportTimestamp_ = input.readInt64();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              methodName_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              app_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return InvocationStatListProto.internal_static_sourceProto_InvocationStatVO_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return InvocationStatListProto.internal_static_sourceProto_InvocationStatVO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InvocationStatVO.class, Builder.class);
    }

    public static final int INVOKETIMES_FIELD_NUMBER = 1;
    private long invokeTimes_;
    /**
     * <code>optional int64 invokeTimes = 1;</code>
     */
    public long getInvokeTimes() {
      return invokeTimes_;
    }

    public static final int INVOKEFAILURETIMES_FIELD_NUMBER = 2;
    private long invokeFailureTimes_;
    /**
     * <code>optional int64 invokeFailureTimes = 2;</code>
     */
    public long getInvokeFailureTimes() {
      return invokeFailureTimes_;
    }

    public static final int INVOKETOTALCOST_FIELD_NUMBER = 3;
    private long invokeTotalCost_;
    /**
     * <code>optional int64 invokeTotalCost = 3;</code>
     */
    public long getInvokeTotalCost() {
      return invokeTotalCost_;
    }

    public static final int INVOKEMINCOST_FIELD_NUMBER = 4;
    private long invokeMinCost_;
    /**
     * <code>optional int64 invokeMinCost = 4;</code>
     */
    public long getInvokeMinCost() {
      return invokeMinCost_;
    }

    public static final int INVOKEMAXCOST_FIELD_NUMBER = 5;
    private long invokeMaxCost_;
    /**
     * <code>optional int64 invokeMaxCost = 5;</code>
     */
    public long getInvokeMaxCost() {
      return invokeMaxCost_;
    }

    public static final int REPORTTIMESTAMP_FIELD_NUMBER = 6;
    private long reportTimestamp_;
    /**
     * <code>optional int64 reportTimestamp = 6;</code>
     */
    public long getReportTimestamp() {
      return reportTimestamp_;
    }

    public static final int METHODNAME_FIELD_NUMBER = 7;
    private volatile Object methodName_;
    /**
     * <code>optional string methodName = 7;</code>
     */
    public String getMethodName() {
      Object ref = methodName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string methodName = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      Object ref = methodName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOST_FIELD_NUMBER = 8;
    private volatile Object host_;
    /**
     * <code>optional string host = 8;</code>
     */
    public String getHost() {
      Object ref = host_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <code>optional string host = 8;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      Object ref = host_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APP_FIELD_NUMBER = 9;
    private volatile Object app_;
    /**
     * <code>optional string app = 9;</code>
     */
    public String getApp() {
      Object ref = app_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        app_ = s;
        return s;
      }
    }
    /**
     * <code>optional string app = 9;</code>
     */
    public com.google.protobuf.ByteString
        getAppBytes() {
      Object ref = app_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        app_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (invokeTimes_ != 0L) {
        output.writeInt64(1, invokeTimes_);
      }
      if (invokeFailureTimes_ != 0L) {
        output.writeInt64(2, invokeFailureTimes_);
      }
      if (invokeTotalCost_ != 0L) {
        output.writeInt64(3, invokeTotalCost_);
      }
      if (invokeMinCost_ != 0L) {
        output.writeInt64(4, invokeMinCost_);
      }
      if (invokeMaxCost_ != 0L) {
        output.writeInt64(5, invokeMaxCost_);
      }
      if (reportTimestamp_ != 0L) {
        output.writeInt64(6, reportTimestamp_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, methodName_);
      }
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, host_);
      }
      if (!getAppBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, app_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (invokeTimes_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, invokeTimes_);
      }
      if (invokeFailureTimes_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, invokeFailureTimes_);
      }
      if (invokeTotalCost_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, invokeTotalCost_);
      }
      if (invokeMinCost_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, invokeMinCost_);
      }
      if (invokeMaxCost_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, invokeMaxCost_);
      }
      if (reportTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, reportTimestamp_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, methodName_);
      }
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, host_);
      }
      if (!getAppBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, app_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof InvocationStatVO)) {
        return super.equals(obj);
      }
      InvocationStatVO other = (InvocationStatVO) obj;

      boolean result = true;
      result = result && (getInvokeTimes()
          == other.getInvokeTimes());
      result = result && (getInvokeFailureTimes()
          == other.getInvokeFailureTimes());
      result = result && (getInvokeTotalCost()
          == other.getInvokeTotalCost());
      result = result && (getInvokeMinCost()
          == other.getInvokeMinCost());
      result = result && (getInvokeMaxCost()
          == other.getInvokeMaxCost());
      result = result && (getReportTimestamp()
          == other.getReportTimestamp());
      result = result && getMethodName()
          .equals(other.getMethodName());
      result = result && getHost()
          .equals(other.getHost());
      result = result && getApp()
          .equals(other.getApp());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + INVOKETIMES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInvokeTimes());
      hash = (37 * hash) + INVOKEFAILURETIMES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInvokeFailureTimes());
      hash = (37 * hash) + INVOKETOTALCOST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInvokeTotalCost());
      hash = (37 * hash) + INVOKEMINCOST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInvokeMinCost());
      hash = (37 * hash) + INVOKEMAXCOST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInvokeMaxCost());
      hash = (37 * hash) + REPORTTIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReportTimestamp());
      hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + APP_FIELD_NUMBER;
      hash = (53 * hash) + getApp().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static InvocationStatVO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InvocationStatVO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InvocationStatVO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InvocationStatVO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InvocationStatVO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static InvocationStatVO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static InvocationStatVO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static InvocationStatVO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static InvocationStatVO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static InvocationStatVO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(InvocationStatVO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sourceProto.InvocationStatVO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sourceProto.InvocationStatVO)
        InvocationStatVOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return InvocationStatListProto.internal_static_sourceProto_InvocationStatVO_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return InvocationStatListProto.internal_static_sourceProto_InvocationStatVO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                InvocationStatVO.class, Builder.class);
      }

      // Construct using com.illegalaccess.rest.monitor.client.vo.proto.InvocationStatListProto.InvocationStatVO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        invokeTimes_ = 0L;

        invokeFailureTimes_ = 0L;

        invokeTotalCost_ = 0L;

        invokeMinCost_ = 0L;

        invokeMaxCost_ = 0L;

        reportTimestamp_ = 0L;

        methodName_ = "";

        host_ = "";

        app_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return InvocationStatListProto.internal_static_sourceProto_InvocationStatVO_descriptor;
      }

      public InvocationStatVO getDefaultInstanceForType() {
        return InvocationStatVO.getDefaultInstance();
      }

      public InvocationStatVO build() {
        InvocationStatVO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public InvocationStatVO buildPartial() {
        InvocationStatVO result = new InvocationStatVO(this);
        result.invokeTimes_ = invokeTimes_;
        result.invokeFailureTimes_ = invokeFailureTimes_;
        result.invokeTotalCost_ = invokeTotalCost_;
        result.invokeMinCost_ = invokeMinCost_;
        result.invokeMaxCost_ = invokeMaxCost_;
        result.reportTimestamp_ = reportTimestamp_;
        result.methodName_ = methodName_;
        result.host_ = host_;
        result.app_ = app_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof InvocationStatVO) {
          return mergeFrom((InvocationStatVO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(InvocationStatVO other) {
        if (other == InvocationStatVO.getDefaultInstance()) return this;
        if (other.getInvokeTimes() != 0L) {
          setInvokeTimes(other.getInvokeTimes());
        }
        if (other.getInvokeFailureTimes() != 0L) {
          setInvokeFailureTimes(other.getInvokeFailureTimes());
        }
        if (other.getInvokeTotalCost() != 0L) {
          setInvokeTotalCost(other.getInvokeTotalCost());
        }
        if (other.getInvokeMinCost() != 0L) {
          setInvokeMinCost(other.getInvokeMinCost());
        }
        if (other.getInvokeMaxCost() != 0L) {
          setInvokeMaxCost(other.getInvokeMaxCost());
        }
        if (other.getReportTimestamp() != 0L) {
          setReportTimestamp(other.getReportTimestamp());
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          onChanged();
        }
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (!other.getApp().isEmpty()) {
          app_ = other.app_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        InvocationStatVO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (InvocationStatVO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long invokeTimes_ ;
      /**
       * <code>optional int64 invokeTimes = 1;</code>
       */
      public long getInvokeTimes() {
        return invokeTimes_;
      }
      /**
       * <code>optional int64 invokeTimes = 1;</code>
       */
      public Builder setInvokeTimes(long value) {
        
        invokeTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 invokeTimes = 1;</code>
       */
      public Builder clearInvokeTimes() {
        
        invokeTimes_ = 0L;
        onChanged();
        return this;
      }

      private long invokeFailureTimes_ ;
      /**
       * <code>optional int64 invokeFailureTimes = 2;</code>
       */
      public long getInvokeFailureTimes() {
        return invokeFailureTimes_;
      }
      /**
       * <code>optional int64 invokeFailureTimes = 2;</code>
       */
      public Builder setInvokeFailureTimes(long value) {
        
        invokeFailureTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 invokeFailureTimes = 2;</code>
       */
      public Builder clearInvokeFailureTimes() {
        
        invokeFailureTimes_ = 0L;
        onChanged();
        return this;
      }

      private long invokeTotalCost_ ;
      /**
       * <code>optional int64 invokeTotalCost = 3;</code>
       */
      public long getInvokeTotalCost() {
        return invokeTotalCost_;
      }
      /**
       * <code>optional int64 invokeTotalCost = 3;</code>
       */
      public Builder setInvokeTotalCost(long value) {
        
        invokeTotalCost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 invokeTotalCost = 3;</code>
       */
      public Builder clearInvokeTotalCost() {
        
        invokeTotalCost_ = 0L;
        onChanged();
        return this;
      }

      private long invokeMinCost_ ;
      /**
       * <code>optional int64 invokeMinCost = 4;</code>
       */
      public long getInvokeMinCost() {
        return invokeMinCost_;
      }
      /**
       * <code>optional int64 invokeMinCost = 4;</code>
       */
      public Builder setInvokeMinCost(long value) {
        
        invokeMinCost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 invokeMinCost = 4;</code>
       */
      public Builder clearInvokeMinCost() {
        
        invokeMinCost_ = 0L;
        onChanged();
        return this;
      }

      private long invokeMaxCost_ ;
      /**
       * <code>optional int64 invokeMaxCost = 5;</code>
       */
      public long getInvokeMaxCost() {
        return invokeMaxCost_;
      }
      /**
       * <code>optional int64 invokeMaxCost = 5;</code>
       */
      public Builder setInvokeMaxCost(long value) {
        
        invokeMaxCost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 invokeMaxCost = 5;</code>
       */
      public Builder clearInvokeMaxCost() {
        
        invokeMaxCost_ = 0L;
        onChanged();
        return this;
      }

      private long reportTimestamp_ ;
      /**
       * <code>optional int64 reportTimestamp = 6;</code>
       */
      public long getReportTimestamp() {
        return reportTimestamp_;
      }
      /**
       * <code>optional int64 reportTimestamp = 6;</code>
       */
      public Builder setReportTimestamp(long value) {
        
        reportTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 reportTimestamp = 6;</code>
       */
      public Builder clearReportTimestamp() {
        
        reportTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private Object methodName_ = "";
      /**
       * <code>optional string methodName = 7;</code>
       */
      public String getMethodName() {
        Object ref = methodName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string methodName = 7;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string methodName = 7;</code>
       */
      public Builder setMethodName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string methodName = 7;</code>
       */
      public Builder clearMethodName() {
        
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string methodName = 7;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        methodName_ = value;
        onChanged();
        return this;
      }

      private Object host_ = "";
      /**
       * <code>optional string host = 8;</code>
       */
      public String getHost() {
        Object ref = host_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string host = 8;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string host = 8;</code>
       */
      public Builder setHost(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string host = 8;</code>
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>optional string host = 8;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private Object app_ = "";
      /**
       * <code>optional string app = 9;</code>
       */
      public String getApp() {
        Object ref = app_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          app_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string app = 9;</code>
       */
      public com.google.protobuf.ByteString
          getAppBytes() {
        Object ref = app_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          app_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string app = 9;</code>
       */
      public Builder setApp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        app_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string app = 9;</code>
       */
      public Builder clearApp() {
        
        app_ = getDefaultInstance().getApp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string app = 9;</code>
       */
      public Builder setAppBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        app_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:sourceProto.InvocationStatVO)
    }

    // @@protoc_insertion_point(class_scope:sourceProto.InvocationStatVO)
    private static final InvocationStatVO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new InvocationStatVO();
    }

    public static InvocationStatVO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InvocationStatVO>
        PARSER = new com.google.protobuf.AbstractParser<InvocationStatVO>() {
      public InvocationStatVO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new InvocationStatVO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InvocationStatVO> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<InvocationStatVO> getParserForType() {
      return PARSER;
    }

    public InvocationStatVO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sourceProto_InvocationStatListVO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sourceProto_InvocationStatListVO_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sourceProto_InvocationStatVO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sourceProto_InvocationStatVO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016StatList.proto\022\013sourceProto\"I\n\024Invocat" +
      "ionStatListVO\0221\n\nstatVOList\030\001 \003(\0132\035.sour" +
      "ceProto.InvocationStatVO\"\322\001\n\020InvocationS" +
      "tatVO\022\023\n\013invokeTimes\030\001 \001(\003\022\032\n\022invokeFail" +
      "ureTimes\030\002 \001(\003\022\027\n\017invokeTotalCost\030\003 \001(\003\022" +
      "\025\n\rinvokeMinCost\030\004 \001(\003\022\025\n\rinvokeMaxCost\030" +
      "\005 \001(\003\022\027\n\017reportTimestamp\030\006 \001(\003\022\022\n\nmethod" +
      "Name\030\007 \001(\t\022\014\n\004host\030\010 \001(\t\022\013\n\003app\030\t \001(\tBI\n" +
      ".com.illegalaccess.rest.monitor.client.v" +
      "o.protoB\027InvocationStatListProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sourceProto_InvocationStatListVO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sourceProto_InvocationStatListVO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sourceProto_InvocationStatListVO_descriptor,
        new String[] { "StatVOList", });
    internal_static_sourceProto_InvocationStatVO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sourceProto_InvocationStatVO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sourceProto_InvocationStatVO_descriptor,
        new String[] { "InvokeTimes", "InvokeFailureTimes", "InvokeTotalCost", "InvokeMinCost", "InvokeMaxCost", "ReportTimestamp", "MethodName", "Host", "App", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
